# Generated by Django 5.0.6 on 2024-05-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_user_name_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='created_date_entry',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_date_user',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
