# Generated by Django 5.0.6 on 2024-05-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0003_alter_entry_created_date_entry_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_date_entry']},
        ),
    ]
