# Generated by Django 5.0.6 on 2024-05-24 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0006_alter_entry_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'ordering': ['-created_entry'], 'verbose_name': 'Entry', 'verbose_name_plural': 'Entries'},
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='created',
            new_name='created_entry',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='created_date_user',
            new_name='created',
        ),
    ]
