# Generated by Django 5.0.6 on 2024-06-04 08:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("guests", "0009_alter_entry_options_alter_entry_message_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="entry",
            options={
                "ordering": ["-created_entry"],
                "verbose_name": "Entry",
                "verbose_name_plural": "Entries",
            },
        ),
        migrations.AlterField(
            model_name="entry",
            name="subject",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="entry",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_entries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
